package edu.farmingdale.advancedprogramming_capstone_project;

import javafx.fxml.FXML;
import javafx.scene.control.TextArea;

/**
 * SummaryController handles displaying the AI-generated lesson summary.
 */
public class SummaryController {
    @FXML private TextArea summaryTextArea;  // Text area to show the summary

    /**
     * Sets the summary text in the UI.
     *
     * @param summary The summary generated by the AI.
     */
    public void setSummary(String summary) {
        summaryTextArea.setText(summary);
    }
}

