package edu.farmingdale.advancedprogramming_capstone_project;

import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.TextArea;

/**
 * SummaryController handles displaying the AI-generated session summary.
 */
public class SummaryController {
    @FXML private TextArea summaryTextArea;

    /**
     * sets summary text to be changed and wrapped
     */
    @FXML
    public void initialize() {
        summaryTextArea.setEditable(true);
        summaryTextArea.setWrapText(true);
        clearSummary();
    }

    /**
     * @param summary The summary generated by the AI.
     */
    public void displaySummary(String summary) {
        Platform.runLater(() -> {
            if (summary != null && !summary.isEmpty()) {
                summaryTextArea.setText(summary);
            } else {
                summaryTextArea.setText("Summary Could Not Be Generated Or Empty");
            }
        });
    }

    /**
     * Clears the summary text in the UI.
     */
    public void clearSummary() {
        Platform.runLater(() -> summaryTextArea.setText("Summary Will Appear Here After Transcription Ends & Processing Completes"));
    }

    /**
     * Sets the summary text in the UI.
     * @param summary The summary generated by the AI.
     */
    public void setSummary(String summary) {
        summaryTextArea.setText(summary);
    }
}